<?php

/**
 * @file
 * Contains student_clubs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function student_clubs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the student_clubs module.
    case 'help.page.student_clubs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function student_clubs_theme() {
  return [
    'student_clubs' => [
      'render element' => 'children',
    ],
  ];
}
