<?php

/**
 * @file
 * Contains testimonials.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function testimonials_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the testimonials module.
    case 'help.page.testimonials':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('importing testimonials content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function testimonials_theme() {
  return [
    'testimonials' => [
      'render element' => 'children',
    ],
  ];
}
