<?php

/**
 * @file
 * Contains fest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fest module.
    case 'help.page.fest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Importing fest content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fest_theme() {
  return [
    'fest' => [
      'render element' => 'children',
    ],
  ];
}
