<?php

/**
 * @file
 * Contains international_transfer_program.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function international_transfer_program_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the international_transfer_program module.
    case 'help.page.international_transfer_program':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Importing itp content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function international_transfer_program_theme() {
  return [
    'international_transfer_program' => [
      'render element' => 'children',
    ],
  ];
}
